### list server
GET http://127.0.0.1:8080/admin/server/list-server?page=1&size=10
accept: */*
Content-Type: application/json
Session: 2cebdf15d414b6713672475a21f995a0

### list worker
GET http://127.0.0.1:8080/admin/worker/list?namespaceId=1&appName=pen&appId=1&page=1&size=10
accept: */*
Content-Type: application/json
Session: 2cebdf15d414b6713672475a21f995a0


### list job slots
GET http://127.0.0.1:8080/admin/server/list-job-slots?page=1&size=10
accept: */*
Content-Type: application/json
Session: 2cebdf15d414b6713672475a21f995a0

